// Mocks generated by Mockito 5.0.15 from annotations
// in restaurant/test/data/source/network/network_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:restaurant/data/model/restaurant/restaurant_model.dart' as _i2;
import 'package:restaurant/data/source/network/network_repository.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeRestaurantResponse_0 extends _i1.Fake
    implements _i2.RestaurantResponse {}

/// A class which mocks [NetworkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkRepository extends _i1.Mock implements _i3.NetworkRepository {
  MockNetworkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RestaurantResponse> getRestaurants() => (super.noSuchMethod(
          Invocation.method(#getRestaurants, []),
          returnValue:
              Future<_i2.RestaurantResponse>.value(_FakeRestaurantResponse_0()))
      as _i4.Future<_i2.RestaurantResponse>);
  @override
  String toString() => super.toString();
}
